"""
Meta Ads Routes - FastAPI endpoints for Meta Ads + Claude integration.
"""

from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from meta_ads_service import MetaAdsService, MetaAdsConfig, MetaAdsAPIError
import claude_ad_service


router = APIRouter(prefix="/api/meta-ads", tags=["meta-ads"])

# Shared service instance (initialized lazily)
_meta_service: Optional[MetaAdsService] = None


def get_meta_service() -> MetaAdsService:
    global _meta_service
    if _meta_service is None:
        _meta_service = MetaAdsService()
    return _meta_service


# ── Pydantic request models ───────────────────────────────────────────


class ConfigUpdate(BaseModel):
    access_token: str
    ad_account_id: str
    page_id: str = ""


class GenerateAdCopyRequest(BaseModel):
    product_name: str
    product_description: str
    target_audience: str = ""
    tone: str = "professional"
    landing_page_url: str = ""
    num_variations: int = 3


class GenerateTargetingRequest(BaseModel):
    product_name: str
    product_description: str
    current_audience: str = ""


class GenerateCampaignRequest(BaseModel):
    product_name: str
    product_description: str
    goal: str = "awareness"
    budget_dollars: float = 50.0
    duration_days: int = 7
    target_audience: str = ""
    landing_page_url: str = ""
    tone: str = "professional"


class CreateCampaignRequest(BaseModel):
    name: str
    objective: str = "OUTCOME_AWARENESS"
    status: str = "PAUSED"
    special_ad_categories: list[str] = []
    daily_budget: Optional[int] = None
    lifetime_budget: Optional[int] = None


class CreateAdSetRequest(BaseModel):
    name: str
    campaign_id: str
    daily_budget: int
    optimization_goal: str = "REACH"
    billing_event: str = "IMPRESSIONS"
    bid_amount: Optional[int] = None
    targeting: Optional[dict] = None
    status: str = "PAUSED"
    start_time: Optional[str] = None
    end_time: Optional[str] = None


class CreateAdCreativeRequest(BaseModel):
    name: str
    page_id: str = ""
    link: str
    message: str
    headline: str
    description: str
    image_hash: Optional[str] = None
    image_url: Optional[str] = None
    call_to_action_type: str = "LEARN_MORE"


class CreateAdRequest(BaseModel):
    name: str
    adset_id: str
    creative_id: str
    status: str = "PAUSED"


class DeployCampaignRequest(BaseModel):
    """Deploy a full campaign plan generated by Claude."""
    campaign_plan: dict
    landing_page_url: str = ""
    image_url: str = ""
    page_id: str = ""


# ── Configuration ─────────────────────────────────────────────────────


@router.get("/config")
async def get_config():
    """Get current Meta Ads configuration (tokens are masked)."""
    svc = get_meta_service()
    token = svc.config.access_token
    return {
        "configured": svc.config.is_configured,
        "access_token_set": bool(token),
        "access_token_preview": f"{token[:8]}...{token[-4:]}" if len(token) > 12 else ("***" if token else ""),
        "ad_account_id": svc.config.ad_account_id,
        "page_id": svc.config.page_id,
    }


@router.post("/config")
async def update_config(req: ConfigUpdate):
    """Update Meta Ads configuration (stored in memory only)."""
    global _meta_service
    config = MetaAdsConfig(
        access_token=req.access_token,
        ad_account_id=req.ad_account_id,
        page_id=req.page_id,
    )
    _meta_service = MetaAdsService(config)
    return {"status": "updated", "configured": config.is_configured}


# ── Claude AI Generation ──────────────────────────────────────────────


@router.post("/generate/ad-copy")
async def generate_ad_copy(req: GenerateAdCopyRequest):
    """Use Claude to generate ad copy variations."""
    try:
        result = await claude_ad_service.generate_ad_copy(
            product_name=req.product_name,
            product_description=req.product_description,
            target_audience=req.target_audience,
            tone=req.tone,
            landing_page_url=req.landing_page_url,
            num_variations=req.num_variations,
        )
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/generate/targeting")
async def generate_targeting(req: GenerateTargetingRequest):
    """Use Claude to suggest targeting parameters."""
    try:
        result = await claude_ad_service.generate_targeting_suggestions(
            product_name=req.product_name,
            product_description=req.product_description,
            current_audience=req.current_audience,
        )
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/generate/campaign")
async def generate_campaign(req: GenerateCampaignRequest):
    """Use Claude to generate a complete campaign plan."""
    try:
        result = await claude_ad_service.generate_full_campaign(
            product_name=req.product_name,
            product_description=req.product_description,
            goal=req.goal,
            budget_dollars=req.budget_dollars,
            duration_days=req.duration_days,
            target_audience=req.target_audience,
            landing_page_url=req.landing_page_url,
            tone=req.tone,
        )
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/analyze-performance")
async def analyze_performance(insights_data: dict):
    """Use Claude to analyze campaign performance and suggest optimizations."""
    try:
        result = await claude_ad_service.analyze_ad_performance(insights_data)
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── Meta API: Campaigns ───────────────────────────────────────────────


@router.get("/campaigns")
async def list_campaigns():
    """List all campaigns in the ad account."""
    svc = get_meta_service()
    try:
        return await svc.get_campaigns()
    except MetaAdsAPIError as e:
        raise HTTPException(status_code=400, detail=e.message)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.post("/campaigns")
async def create_campaign(req: CreateCampaignRequest):
    """Create a new campaign."""
    svc = get_meta_service()
    try:
        return await svc.create_campaign(
            name=req.name,
            objective=req.objective,
            status=req.status,
            special_ad_categories=req.special_ad_categories,
            daily_budget=req.daily_budget,
            lifetime_budget=req.lifetime_budget,
        )
    except MetaAdsAPIError as e:
        raise HTTPException(status_code=400, detail=e.message)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.get("/campaigns/{campaign_id}")
async def get_campaign(campaign_id: str):
    """Get a single campaign."""
    svc = get_meta_service()
    try:
        return await svc.get_campaign(campaign_id)
    except MetaAdsAPIError as e:
        raise HTTPException(status_code=400, detail=e.message)


@router.get("/campaigns/{campaign_id}/insights")
async def get_campaign_insights(campaign_id: str, date_preset: str = "last_7d"):
    """Get performance insights for a campaign."""
    svc = get_meta_service()
    try:
        return await svc.get_campaign_insights(campaign_id, date_preset)
    except MetaAdsAPIError as e:
        raise HTTPException(status_code=400, detail=e.message)


# ── Meta API: Ad Sets ─────────────────────────────────────────────────


@router.get("/adsets")
async def list_ad_sets(campaign_id: Optional[str] = None):
    """List ad sets, optionally filtered by campaign."""
    svc = get_meta_service()
    try:
        return await svc.get_ad_sets(campaign_id)
    except MetaAdsAPIError as e:
        raise HTTPException(status_code=400, detail=e.message)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.post("/adsets")
async def create_ad_set(req: CreateAdSetRequest):
    """Create a new ad set."""
    svc = get_meta_service()
    try:
        return await svc.create_ad_set(
            name=req.name,
            campaign_id=req.campaign_id,
            daily_budget=req.daily_budget,
            optimization_goal=req.optimization_goal,
            billing_event=req.billing_event,
            bid_amount=req.bid_amount,
            targeting=req.targeting,
            status=req.status,
            start_time=req.start_time,
            end_time=req.end_time,
        )
    except MetaAdsAPIError as e:
        raise HTTPException(status_code=400, detail=e.message)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


# ── Meta API: Ad Creatives ────────────────────────────────────────────


@router.post("/adcreatives")
async def create_ad_creative(req: CreateAdCreativeRequest):
    """Create an ad creative."""
    svc = get_meta_service()
    page_id = req.page_id or svc.config.page_id
    if not page_id:
        raise HTTPException(status_code=400, detail="page_id is required (set in config or request)")
    try:
        return await svc.create_ad_creative(
            name=req.name,
            page_id=page_id,
            link=req.link,
            message=req.message,
            headline=req.headline,
            description=req.description,
            image_hash=req.image_hash,
            image_url=req.image_url,
            call_to_action_type=req.call_to_action_type,
        )
    except MetaAdsAPIError as e:
        raise HTTPException(status_code=400, detail=e.message)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


# ── Meta API: Ads ─────────────────────────────────────────────────────


@router.get("/ads")
async def list_ads(adset_id: Optional[str] = None):
    """List ads, optionally filtered by ad set."""
    svc = get_meta_service()
    try:
        return await svc.get_ads(adset_id)
    except MetaAdsAPIError as e:
        raise HTTPException(status_code=400, detail=e.message)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.post("/ads")
async def create_ad(req: CreateAdRequest):
    """Create an ad."""
    svc = get_meta_service()
    try:
        return await svc.create_ad(
            name=req.name,
            adset_id=req.adset_id,
            creative_id=req.creative_id,
            status=req.status,
        )
    except MetaAdsAPIError as e:
        raise HTTPException(status_code=400, detail=e.message)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


# ── Deploy Full Campaign ──────────────────────────────────────────────


@router.post("/deploy-campaign")
async def deploy_campaign(req: DeployCampaignRequest):
    """Deploy a Claude-generated campaign plan to Meta Ads.

    This creates the campaign, ad set, creatives, and ads in sequence.
    Everything is created in PAUSED status for review before activation.
    """
    svc = get_meta_service()
    plan = req.campaign_plan
    page_id = req.page_id or svc.config.page_id

    if not page_id:
        raise HTTPException(status_code=400, detail="page_id is required")

    results = {"campaign": None, "ad_set": None, "creatives": [], "ads": []}

    try:
        # 1. Create campaign
        camp_data = plan["campaign"]
        campaign = await svc.create_campaign(
            name=camp_data["name"],
            objective=camp_data["objective"],
            status="PAUSED",
            special_ad_categories=camp_data.get("special_ad_categories", []),
            daily_budget=camp_data.get("daily_budget_cents"),
        )
        campaign_id = campaign["id"]
        results["campaign"] = campaign

        # 2. Create ad set
        adset_data = plan["ad_set"]
        ad_set = await svc.create_ad_set(
            name=adset_data["name"],
            campaign_id=campaign_id,
            daily_budget=camp_data.get("daily_budget_cents", 5000),
            optimization_goal=adset_data.get("optimization_goal", "REACH"),
            billing_event=adset_data.get("billing_event", "IMPRESSIONS"),
            targeting=adset_data.get("targeting"),
            status="PAUSED",
        )
        adset_id = ad_set["id"]
        results["ad_set"] = ad_set

        # 3. Create creatives and ads
        for creative_data in plan.get("ad_creatives", []):
            creative = await svc.create_ad_creative(
                name=creative_data["name"],
                page_id=page_id,
                link=req.landing_page_url or "https://example.com",
                message=creative_data["primary_text"],
                headline=creative_data["headline"],
                description=creative_data["description"],
                image_url=req.image_url or None,
                call_to_action_type=creative_data.get("call_to_action", "LEARN_MORE"),
            )
            results["creatives"].append(creative)

            ad = await svc.create_ad(
                name=f"Ad - {creative_data['name']}",
                adset_id=adset_id,
                creative_id=creative["id"],
                status="PAUSED",
            )
            results["ads"].append(ad)

        return {"status": "deployed", "results": results}

    except MetaAdsAPIError as e:
        raise HTTPException(
            status_code=400,
            detail=f"Meta API error during deployment: {e.message}. Partial results: {results}",
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


# ── Insights ──────────────────────────────────────────────────────────


@router.get("/insights")
async def get_account_insights(date_preset: str = "last_7d"):
    """Get account-level performance insights."""
    svc = get_meta_service()
    try:
        return await svc.get_account_insights(date_preset)
    except MetaAdsAPIError as e:
        raise HTTPException(status_code=400, detail=e.message)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


# ── Targeting Search ──────────────────────────────────────────────────


@router.get("/targeting-search")
async def search_targeting(q: str, target_type: str = "adinterest"):
    """Search Meta's targeting options (interests, behaviors, etc.)."""
    svc = get_meta_service()
    try:
        return await svc.search_targeting(q, target_type)
    except MetaAdsAPIError as e:
        raise HTTPException(status_code=400, detail=e.message)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
